[package]
name = "vial-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
serde.workspace = true

serde_json = "1.0.149"
postcard = { version = "1.1.3", features = ["use-std"] }
