[package]
name = "vial-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true

postcard = { version = "1.1.3", features = ["use-std"] }
